<a href="https://colab.research.google.com/github/nogood1014/2020-2-AI/blob/main/code/01_tf_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
# 텐서플로 1.0 버전 선택
try:
    # %tensorflow_version only exists in Colab.
    %tensorflow_version 1.x
except Exception:
    pass

import tensorflow as tf
tf.__version__

'1.15.2'

↓결과 값에 나타나는 b는 byte타입을 뜻함

In [ ]:
import tensorflow as tf

hello = tf.constant('Hello World!')

sess = tf.Session()
print(sess.run(hello))
sess.close()

b'Hello World!'


↓Tensor(이름, 형태(()는 스칼라를 뜻함), 타입정보)

In [ ]:
a = 10 
b = 10
print(tf.add(a,b))

sess = tf.Session()
print(sess.run(tf.add(a,b)))
sess.close()

Tensor("Add:0", shape=(), dtype=int32)
20


**if 이미 1.x을 사용 중이라면 -> 메뉴,런타임 | 런타임 다시 시작 (단축키 :ctrl+M.)**

In [ ]:
import tensorflow as tf
tf.__version__

'2.3.0'

↓2.x 버전에서는 session없이도 계산 값 출력 가능

In [ ]:
a = tf.constant(5)
b = tf.constant(3)
print(a+b)

tf.Tensor(8, shape=(), dtype=int32)


↓값만 보고 싶으면 메소드 numpy() 사용

In [ ]:
c = tf.constant('Hello, World')
print(c)
print(c.numpy())

tf.Tensor(b'Hello, World', shape=(), dtype=string)
b'Hello, World'


In [ ]:
a = tf.constant(3)
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
a.shape

TensorShape([])

In [ ]:
a.dtype

tf.int32

In [ ]:
a.numpy()

3

In [ ]:
b = tf.constant(3.)
b

<tf.Tensor: shape=(), dtype=float32, numpy=3.0>

In [ ]:
b.shape

TensorShape([])

In [ ]:
b.dtype

tf.float32

In [ ]:
b.numpy()

3.0

#**Tensor Shapes, type code**

↓Vector

In [ ]:
a = tf.constant([1,2,3])
a.shape

TensorShape([3])

↓Matrix(행렬) - 2행 3열  

In [ ]:
a = tf.constant([[1,2,3],[4,5,6]])
a.shape

TensorShape([2, 3])

↓n차원 행렬 (2 * 2 * 3)

In [ ]:
a = tf.constant([[[1,2,3], [4,5,6,]],[[1,2,3],[4,5,6]]])
a.shape

TensorShape([2, 2, 3])

In [ ]:
a

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

#**조건 연산 tf.cond()**

> tf.cond (
  pred, true_fn = None, false_fn = None, name = None)

pred를 검사해 참이면 true_fc 반환, 거짓이면 false_fc 반환

↓ bool이 true이면 2.0 반환, bool이 false이면 11.0 반환

In [ ]:
x = tf.constant(1.)
bool = tf.constant(True)
res = tf.cond(bool,lambda: tf.add(x, 1.), lambda: tf.add(x, 10.))

print(res)
print(res.numpy())

tf.Tensor(2.0, shape=(), dtype=float32)
2.0


↓less(x,y) 의 의미는 x<y와 같다 (참 : 34 , 거짓 : 28)

In [ ]:
x = tf.constant(2)
y = tf.constant(5)
def f1(): return tf.multiply(x, 17)
def f2(): return tf.add(y, 23)
r = tf.cond(tf.less(x,y), f1, f2)

r.numpy()

34

#**1차원 배열 텐서**

In [ ]:
t = tf.constant([1,2,3])
t

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

**↓(중요)텐서와 텐서의 합은 각각의 값끼리 더해진다**

In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([5,6,7])

print((x+y).numpy())

[ 6  8 10]


In [ ]:
a = tf.constant([5], dtype=tf.float32)
b = tf.constant([10], dtype=tf.float32)
c = tf.constant([2], dtype=tf.float32)
print(a.numpy())

d = a * b + c

print(d)
print(d.numpy())

[5.]
tf.Tensor([52.], shape=(1,), dtype=float32)
[52.]


## **(!!매우 중요)텐서의 브로드캐스팅**
- shape이 다르더라도 연산이 가능하도록





In [ ]:
x = tf.constant([[0], [10], [20], [30]])
y = tf.constant([0, 1, 2])

print((x+y).numpy())

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


↓[0 1 2] +[5] -> [0 1 2] + [5 5 5] 
각 자리 수의 합 


In [ ]:
import numpy as np

print(np.arange(3))
print(np.ones((3,3)))
print()

x = tf.constant((np.arange(3)))
y = tf.constant([5], dtype=tf.int64)
print(x)
print(y)
print(x+y)


[0 1 2]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

tf.Tensor([0 1 2], shape=(3,), dtype=int64)
tf.Tensor([5], shape=(1,), dtype=int64)
tf.Tensor([5 6 7], shape=(3,), dtype=int64)


**↓ 2번째 문단 문제 중간고사! 너무 중요!**</br>
2) dtype 지정 이유 : 위 ones(3,3)의 데이터 타입이 double이기 때문에 통일해 줌

In [ ]:
x = tf.constant((np.arange (3)))
y = tf.constant((5), dtype=tf.int64) 
print((x+y).numpy())

# 중간고사 제출 합니다!
x = tf.constant((np.ones((3, 3)))) 
y = tf.constant(np.arange (3), dtype=tf.double) # 위 dtype과 맞춰 주기 위해
print((x+y).numpy())

x = tf.constant(np.arange(3).reshape(3, 1)) 
y = tf.constant (np.arange(3)) 
print ((x+y).numpy())

[5 6 7]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]
